### ISSUE TITLE
How to inject the generated lua file into the map?

### ISSUE THREAD

**Issue by lhing17** [Indaxia/wc3-wlpm-module-manager#1]
Your wlpm module manager is cooool. But I'd like to know how to convert my war3map.lua file into GUI after wlpm build, like you've done in your demo map?

**Comment by ScorpioT1000** [comment]
Work with the map as a directory. There are some 1.31+ MPQ library problems so I've not implemented mpq support for now. Waiting for a stable mpq dll.

You can just test your map in a map-as-a-directory mode. But when you want to publish/share, insert the war3map.lua manually using Ladik's Mpq Editor: https://www.hiveworkshop.com/threads/ladiks-mpq-editor-32bit.249562/

**Comment by lhing17** [comment]
thx for the reply:<)
